version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    environment:
      POSTGRES_DB: semantic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5415:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: