server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/semantic_db
    username: postgres
    password: postgres

  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text

    vectorstore:
      pgvector:
        initialize-schema: true
